// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/davco01a/kabanero-rest-services/models"
)

// GetTestOKCode is the HTTP code returned for type GetTestOK
const GetTestOKCode int = 200

/*GetTestOK standard message response

swagger:response getTestOK
*/
type GetTestOK struct {

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewGetTestOK creates GetTestOK with default headers values
func NewGetTestOK() *GetTestOK {

	return &GetTestOK{}
}

// WithPayload adds the payload to the get test o k response
func (o *GetTestOK) WithPayload(payload *models.Message) *GetTestOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get test o k response
func (o *GetTestOK) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
