// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/davco01a/kabanero-rest-services/models"
)

// DescribeOKCode is the HTTP code returned for type DescribeOK
const DescribeOKCode int = 200

/*DescribeOK describe stack

swagger:response describeOK
*/
type DescribeOK struct {

	/*
	  In: Body
	*/
	Payload *models.DescribeStack `json:"body,omitempty"`
}

// NewDescribeOK creates DescribeOK with default headers values
func NewDescribeOK() *DescribeOK {

	return &DescribeOK{}
}

// WithPayload adds the payload to the describe o k response
func (o *DescribeOK) WithPayload(payload *models.DescribeStack) *DescribeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the describe o k response
func (o *DescribeOK) SetPayload(payload *models.DescribeStack) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DescribeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
