// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kabanero-io/kabanero-rest-services/models"
)

// PostLoginCreatedCode is the HTTP code returned for type PostLoginCreated
const PostLoginCreatedCode int = 201

/*PostLoginCreated login successful

swagger:response postLoginCreated
*/
type PostLoginCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Jwt `json:"body,omitempty"`
}

// NewPostLoginCreated creates PostLoginCreated with default headers values
func NewPostLoginCreated() *PostLoginCreated {

	return &PostLoginCreated{}
}

// WithPayload adds the payload to the post login created response
func (o *PostLoginCreated) WithPayload(payload *models.Jwt) *PostLoginCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post login created response
func (o *PostLoginCreated) SetPayload(payload *models.Jwt) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostLoginCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostLoginDefault error

swagger:response postLoginDefault
*/
type PostLoginDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostLoginDefault creates PostLoginDefault with default headers values
func NewPostLoginDefault(code int) *PostLoginDefault {
	if code <= 0 {
		code = 500
	}

	return &PostLoginDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post login default response
func (o *PostLoginDefault) WithStatusCode(code int) *PostLoginDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post login default response
func (o *PostLoginDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post login default response
func (o *PostLoginDefault) WithPayload(payload *models.Error) *PostLoginDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post login default response
func (o *PostLoginDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostLoginDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
