// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Kabanero REST API
//
//  For the Kabanero REST service
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/io.goswagger.examples.todo-list.v1+json
//
//  Produces:
//    - application/io.goswagger.examples.todo-list.v1+json
//
// swagger:meta
package restapi
