// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/io.goswagger.examples.todo-list.v1+json"
  ],
  "produces": [
    "application/io.goswagger.examples.todo-list.v1+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "For the Kabanero REST service",
    "title": "Kabanero REST API",
    "version": "1.0.0"
  },
  "paths": {
    "/": {
      "get": {
        "tags": [
          "message"
        ],
        "responses": {
          "200": {
            "description": "standard message response",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/credentials"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "login successful",
            "schema": {
              "$ref": "#/definitions/jwt"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/test": {
      "get": {
        "tags": [
          "message"
        ],
        "responses": {
          "200": {
            "description": "standard message response",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      }
    },
    "/v1/describe/stacks/{stackName}/versions/{version}": {
      "get": {
        "operationId": "describe",
        "parameters": [
          {
            "type": "string",
            "name": "stackName",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "version",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "describe stack",
            "schema": {
              "$ref": "#/definitions/describeStack"
            }
          }
        }
      }
    },
    "/v1/stacks": {
      "get": {
        "operationId": "list",
        "responses": {
          "201": {
            "description": "login successful",
            "schema": {
              "$ref": "#/definitions/stacksList"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "commonStack": {
      "type": "object",
      "properties": {
        "exception message": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "versions": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "images": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "image": {
                      "type": "string"
                    }
                  }
                }
              },
              "reponame": {
                "type": "string"
              },
              "version": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "credentials": {
      "type": "object",
      "required": [
        "gituser",
        "gitpat"
      ],
      "properties": {
        "gitpat": {
          "type": "string",
          "minLength": 1
        },
        "gituser": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "describeStack": {
      "type": "object",
      "properties": {
        "digest check": {
          "type": "string"
        },
        "git repo url": {
          "type": "string"
        },
        "image": {
          "type": "string"
        },
        "image digest": {
          "type": "string"
        },
        "kabanero digest": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "project": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "jwt": {
      "type": "object",
      "properties": {
        "jwt": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "kabaneroStack": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "status": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "digest check": {
                "type": "string"
              },
              "image digest": {
                "type": "string"
              },
              "kabanero digest": {
                "type": "string"
              },
              "status": {
                "type": "string"
              },
              "version": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "message": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "stacksList": {
      "type": "object",
      "properties": {
        "activate stacks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/commonStack"
          }
        },
        "curated stacks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/commonStack"
          }
        },
        "kabanero stacks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/kabaneroStack"
          }
        },
        "new curated stacks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/commonStack"
          }
        },
        "obsolete stacks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/commonStack"
          }
        },
        "repositories": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/io.goswagger.examples.todo-list.v1+json"
  ],
  "produces": [
    "application/io.goswagger.examples.todo-list.v1+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "For the Kabanero REST service",
    "title": "Kabanero REST API",
    "version": "1.0.0"
  },
  "paths": {
    "/": {
      "get": {
        "tags": [
          "message"
        ],
        "responses": {
          "200": {
            "description": "standard message response",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/credentials"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "login successful",
            "schema": {
              "$ref": "#/definitions/jwt"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/test": {
      "get": {
        "tags": [
          "message"
        ],
        "responses": {
          "200": {
            "description": "standard message response",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        }
      }
    },
    "/v1/describe/stacks/{stackName}/versions/{version}": {
      "get": {
        "operationId": "describe",
        "parameters": [
          {
            "type": "string",
            "name": "stackName",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "version",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "describe stack",
            "schema": {
              "$ref": "#/definitions/describeStack"
            }
          }
        }
      }
    },
    "/v1/stacks": {
      "get": {
        "operationId": "list",
        "responses": {
          "201": {
            "description": "login successful",
            "schema": {
              "$ref": "#/definitions/stacksList"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CommonStackVersionsItems0": {
      "type": "object",
      "properties": {
        "images": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CommonStackVersionsItems0ImagesItems0"
          }
        },
        "reponame": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    },
    "CommonStackVersionsItems0ImagesItems0": {
      "type": "object",
      "properties": {
        "image": {
          "type": "string"
        }
      }
    },
    "KabaneroStackStatusItems0": {
      "type": "object",
      "properties": {
        "digest check": {
          "type": "string"
        },
        "image digest": {
          "type": "string"
        },
        "kabanero digest": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    },
    "StacksListRepositoriesItems0": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "commonStack": {
      "type": "object",
      "properties": {
        "exception message": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "versions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CommonStackVersionsItems0"
          }
        }
      }
    },
    "credentials": {
      "type": "object",
      "required": [
        "gituser",
        "gitpat"
      ],
      "properties": {
        "gitpat": {
          "type": "string",
          "minLength": 1
        },
        "gituser": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "describeStack": {
      "type": "object",
      "properties": {
        "digest check": {
          "type": "string"
        },
        "git repo url": {
          "type": "string"
        },
        "image": {
          "type": "string"
        },
        "image digest": {
          "type": "string"
        },
        "kabanero digest": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "project": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "jwt": {
      "type": "object",
      "properties": {
        "jwt": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "kabaneroStack": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "status": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/KabaneroStackStatusItems0"
          }
        }
      }
    },
    "message": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "stacksList": {
      "type": "object",
      "properties": {
        "activate stacks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/commonStack"
          }
        },
        "curated stacks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/commonStack"
          }
        },
        "kabanero stacks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/kabaneroStack"
          }
        },
        "new curated stacks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/commonStack"
          }
        },
        "obsolete stacks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/commonStack"
          }
        },
        "repositories": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/StacksListRepositoriesItems0"
          }
        }
      }
    }
  }
}`))
}
