// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Credentials credentials
//
// swagger:model credentials
type Credentials struct {

	// gitpat
	// Required: true
	// Min Length: 1
	Gitpat *string `json:"gitpat"`

	// gituser
	// Required: true
	// Min Length: 1
	Gituser *string `json:"gituser"`
}

// Validate validates this credentials
func (m *Credentials) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGitpat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGituser(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Credentials) validateGitpat(formats strfmt.Registry) error {

	if err := validate.Required("gitpat", "body", m.Gitpat); err != nil {
		return err
	}

	if err := validate.MinLength("gitpat", "body", string(*m.Gitpat), 1); err != nil {
		return err
	}

	return nil
}

func (m *Credentials) validateGituser(formats strfmt.Registry) error {

	if err := validate.Required("gituser", "body", m.Gituser); err != nil {
		return err
	}

	if err := validate.MinLength("gituser", "body", string(*m.Gituser), 1); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Credentials) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Credentials) UnmarshalBinary(b []byte) error {
	var res Credentials
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
