// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StacksList stacks list
//
// swagger:model stacksList
type StacksList struct {

	// kabanero stacks
	KabaneroStacks []*KabaneroStack `json:"kabanero stacks"`
}

// Validate validates this stacks list
func (m *StacksList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKabaneroStacks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StacksList) validateKabaneroStacks(formats strfmt.Registry) error {

	if swag.IsZero(m.KabaneroStacks) { // not required
		return nil
	}

	for i := 0; i < len(m.KabaneroStacks); i++ {
		if swag.IsZero(m.KabaneroStacks[i]) { // not required
			continue
		}

		if m.KabaneroStacks[i] != nil {
			if err := m.KabaneroStacks[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("kabanero stacks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *StacksList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StacksList) UnmarshalBinary(b []byte) error {
	var res StacksList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
